### ISSUE TITLE
Examples

### ISSUE THREAD

**Issue by andyschmidt** [kevindew/openapi3_parser#11]
Hi,

I need to make a text-blob containing the request (header and body) out of openapi yaml.
Is there an easy way (e.g. to_http) to do this, or do I have to walk through all paths, parameters on my own? I already walked a long way with pry but I couldn't find some function like that.

I appreciate any hints!

regards, Andy

**Comment by kevindew** [comment]
Hi @andyschmidt, sorry for the very delayed reply. I had thought I had replied long ago. Is this something that is still a concern for you?

**Comment by andyschmidt** [comment]
can we still work on this?
