### ISSUE TITLE
Spelling error with discriminator for oneOf nodes

### ISSUE THREAD

**Issue by kerrgibson** [kevindew/openapi3_parser#12]
Discriminator references for `oneOf` have a spelling error. If I put a _discriminator_ in my schema, it gets referenced by `node.deciminator` instead of `node.descriminator` (the 'r' is missing in the word).

`node.discriminator` gives this error in ruby:
`*** NoMethodError Exception: undefined method 'discriminator' for <Openapi3Parser::Node::Schema:0x00007f9872942480>`

But `node.disciminator`  gives `Openapi3Parser::Node::Discriminator(#/components/schemas/xx/yy/zz/discriminator)`

Workaround is to use `node['descriminator']`

**Comment by kevindew** [comment]
Thank you @kerrgibson - I've fixed this in 0aaf26e5 and have released 0.8.1 with a fix for this issue.

**Comment by kerrgibson** [comment]
Thanks. I like this product.

> On May 11, 2020, at 7:39 PM, Kevin Dew <notifications@github.com> wrote:
> 
> 
> Thank you @kerrgibson <https://url.emailprotection.link/?buEq4eyNl9NRYRhKUfm4VcB3vTj4i-rK8VCwtr1KPZXd2Ge2z3vBuilOCovLd0ur67G-zSMuy-GPyem_4_x3gepB6ci4XnRAKVZg21ioRMOVCzygrCMtKcxUmO-JK3UH5> - I've fixed this in 0aaf26e <https://url.emailprotection.link/?b0x4ul4zOhcIJvZRNeS24AlAEJ55S6QZ8BXaZw2To-NAZiixrI5R1tMuSSGKAHe0ZQpPqWM4hRXfnzB5ecigzPi5XnWJIZrMox70Wys5Evpcf8xvuHrn_NqH061acF0ME8_UXf5f1tNj3QwV5-GfXH0a1P2GDV2O1jS6ij3PlnvQ~> and have released 0.8.1 with a fix for this issue.
> 
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub <https://url.emailprotection.link/?boJyVaA8SwqP41YoEK_LlpCA5bDo3lAQBU7Cj6b02DmT7iagfMD8X6gmh-s3q9kPKOg11eN5oNKxSeeGoqgx44Sp6sEAjENXnhH2nEqPTiN81wTaJ3qv13D2HPHLt_txViNMrna0--q_TIY8ezfUGsHUdejvUE_y6bVgIcsvKTZs~>, or unsubscribe <https://url.emailprotection.link/?byODWZ7yxtiC034i8xyTcEMEFi0Mc5APQZqpek_qGU9uVTFc2DdwZJmNvdjf6LgR0d3Teg_FJZP_105EQzerDAzEH8YUgBhzsw4p65FBuA2DZ8wMmyTH19p_fqxUTxILKCnokQ8esiXfwBYGx808gl2DQUJ08nXneGDGi6dTtsZDb0eocj36SKH4MfZCJYxYOJ6Y_Qu29BPA_zv7MW2xT3w~~>.
> 

William “Kerr” Gibson, CTO
America's Floor Source <http://americasfloorsource.com/>
3442 Millennium Ct., Columbus, Ohio 43219 
Telephone: 614-237-3181 | Fax: 614-237-3405 | Mobile: 614-603-9695
