### ISSUE TITLE
Serialize a Document.

### ISSUE THREAD

**Issue by stefanondisponibile** [kevindew/openapi3_parser#15]
Hello, and thanks for this cool library.
However, how should one serialize the document back once it's been deserialized via `Openapi3Parser.load` or `Openapi3Parser.load_url`?

```
irb(main):001:0> doc = Openapi3Parser.load_url('https://raw.githubusercontent.com/stripe/openapi/master/openapi/spec3.json')
=> Openapi3Parser::Document(openapi_version: 3.0, root_source: Openapi3Parser::Source(input: https://raw.githubusercontent.com/stripe/openapi/master/openapi/spec3.json))
irb(main):002:0> doc.as_json
Traceback (most recent call last):
        1: from (irb):2
SystemStackError (stack level too deep)
```

This was somehow expected, so I've tried with something like `doc.sources.first.data.to_json`, which works in this case but apparently not in other contexts (which I am still investigating).

What is the proper way of serializing a `Openapi3Parser::Document` back?

Thank you!

**Comment by stefanondisponibile** [comment]
Hi @kevindew, thanks for the detailed reply!
Actually the `doc.root_source.data` sounds exactly what I was looking for. The idea would be bridging an ActiveRecord custom field to have a `Openapi3Parser::Document` back when `get`ting it. And it works. What do you think of such an approach?

However, whatever the answer is, I found out that didn't look like an serialization/deserialization problem. If I set up a rails action like this

```ruby
def register
  doc = Openapi3Parser.load_url(params.require(:url))
  puts doc.info
end
```

I got different behaviours when I send these two different `:url`:

`input`: `https://raw.githubusercontent.com/OAI/OpenAPI-Specification/master/examples/v3.0/petstore.yaml`
`outputs`: `#<Openapi3Parser::Node::Info:0x00007ff7ab581218>`

`input`: `https://raw.githubusercontent.com/stripe/openapi/master/openapi/spec3.json`
`outputs`: `SystemStackError (stack level too deep):`


This works also with other `openapi`s documents/urls, it breaks just with the "stripe" one, so I haven't got an idea yet, do you?
Also, should I open a different issue specifically on this? As said, it turned out not being an actual serialization problem as I thought.

Thank you!

**Comment by kevindew** [comment]
Oh great, glad to hear that'll do the trick for you. It makes sense about you wanting to store a local version of what was retrieved online. If I hear of this being a use-case for others I'll have a ponder over how this could be nicer - it feels like it'd be be good to have an approach that resolves any references in external files too and gives a normalised source.

With regards to your issue, are you using the latest version of this gem? I tried it out locally with v0.8.2 (which shipped with a fix for a recursion issue) and didn't experience the same problem with the Stripe API:

```
irb(main):001:0> doc = Openapi3Parser.load_url("https://raw.githubusercontent.com/stripe/openapi/master/openapi/spec3.json")
=> Openapi3Parser::Document(openapi_version: 3.0, root_source: Openapi3Parser::Source(input: https://raw.githubusercontent.com/stripe/openapi/master/openapi/spec3.json))
irb(main):002:0> doc.info
=> Openapi3Parser::Node::Info(#/info)
```

**Comment by stefanondisponibile** [comment]
Thank you! Yes, this approach looks more than enough for now! 🚀🚀🚀

And yep, I'm using the same version:
```
bundle show | grep openapi
* openapi3_parser (0.8.2)
```

it works on the console for me too, but it doesn't inside a rails action. 🧐

**Comment by kevindew** [comment]
I see how strange, I wonder what the cause might be 🤔. It sounds like that is worth opening an issue. It'd be good to see the stacktrace and some instructions to replicate.

**Comment by stefanondisponibile** [comment]
Alright! Then I'll close this issue, put up some better info on the other one to open a specific one on that :) Thanks for the support and the great library!
