### ISSUE TITLE
Openapi3Parser::Node::Schema#requires? incorrectly returns true

### ISSUE THREAD

**Issue by jcoyne** [kevindew/openapi3_parser#20]
If I have two properties that both are refs to the same type and one is required:

```
    AdminPolicyAdministrative:
      type: object
      additionalProperties: false
      properties:
        hasAdminPolicy:
          $ref: '#/components/schemas/Druid'
        referencesAgreement:
          $ref: '#/components/schemas/Druid'
      required:
        - hasAdminPolicy
   ```  

Then when I query the non-required property, `requires?` returns true:

```
(byebug) doc
Openapi3Parser::Node::Schema(#/components/schemas/AdminPolicyAdministrative)
(byebug) properties_doc
Openapi3Parser::Node::Schema(#/components/schemas/AdminPolicyAdministrative/properties/referencesAgreement)
(byebug) doc.requires?(properties_doc)
true
```

However, If i change the required item to a different ref, it does not:

```
    AdminPolicyAdministrative:
      type: object
      additionalProperties: false
      properties:
        hasAdminPolicy:
          $ref: '#/components/schemas/Foo'
        referencesAgreement:
          $ref: '#/components/schemas/Druid'
      required:
        - hasAdminPolicy
   ```  

```
(byebug) doc
Openapi3Parser::Node::Schema(#/components/schemas/AdminPolicyAdministrative)
(byebug) properties_doc
Openapi3Parser::Node::Schema(#/components/schemas/AdminPolicyAdministrative/properties/referencesAgreement)
(byebug) doc.requires?(properties_doc)
false
```

**Comment by jcoyne** [comment]
The problem seems to occur here: https://github.com/kevindew/openapi3_parser/blob/main/lib/openapi3_parser/node/schema.rb#L125 where `Openapi3Parser::Node::Schema(#/components/schemas/AdminPolicyAdministrative/properties/referencesAgreement)` and `Openapi3Parser::Node::Schema(#/components/schemas/AdminPolicyAdministrative/properties/hasAdminPolicy)` are determinted to be equivalent.

**Comment by jcoyne** [comment]
I am able to work around this by passing `doc.requires?('referencesAgreement')` rather than the `Schema` object.

**Comment by kevindew** [comment]
Thanks for opening this and for the detailed information - it made it easy for me to replicate your problem.

This does seem to indicate a problem in the library. I've put together a fix in https://github.com/kevindew/openapi3_parser/commit/7c229f2ab94b933f68a7a93f0bf65fee2a3127dd which I'll look at releasing in the next couple of days. If you have a chance it'd be great if you could try it out to confirm it resolves your problem (and doesn't introduce a fresh one) - you can do so by changing your Gemfile entry to `gem "openapi3_parser", git: "https://github.com/kevindew/openapi3_parser", ref: "7c229f2"`

**Comment by jcoyne** [comment]
I tried that ref and it fixes the problem.
