### ISSUE TITLE
"Unxpected Fields" in Parameter Example with JSON

### ISSUE THREAD

**Issue by jackchi** [kevindew/openapi3_parser#21]
I assume this is similar to https://github.com/kevindew/openapi3_parser/pull/19

I am using the latest `0.9.0` version but still getting:

```bash
Openapi3Parser.load_file("swagger_v3.json")
Generated swagger file found to be invalid: swagger/v3.json
Error count: 302
source_location: #/paths//api/v3/files/{file_uuid}/get/responses/200 (Response): Unexpected fields: examples
source_location: #/paths//api/v3/files/{file_uuid}/get/responses/403 (Response): Unexpected fields: examples
source_location: #/paths//api/v3/files/{file_uuid}/get/responses/404 (Response): Unexpected fields: examples
```

Could it be they are loading by yaml and I am loading by JSON?

**Comment by kevindew** [comment]
Hi @jackchi - sorry for the delay I missed this issue come in.

You've probably long moved on with your life now but as I understand from your output it looks like the error is the presence of "examples" fields in [Response objects](https://swagger.io/specification/#response-object):

e.g you have a structure like:

```yaml
responses:
  '200':
    examples:
      example_1:
        value: test
    description: An array of products
    content:
      application/json:
        schema:
          $ref: "#/components/schemas/ProductList"
```

Whereas the examples field is a property of a [MediaType object](https://swagger.io/specification/#media-type-object) not a response

So the above would be valid as:

```yaml
responses:
  '200':
    description: An array of products
    content:
      application/json:
        examples:
          example_1:
            value: test
        schema:
          $ref: "#/components/schemas/ProductList"
```
