### ISSUE TITLE
Narrowing a type down to null in OpenAPI v3.0 produces invalid object errors

### ISSUE THREAD

**Issue by backus** [kevindew/openapi3_parser#23]
Hi there! I've had to do a ton of OpenAPI related processing work in the past month and I wanted to start by saying this gem is great and you did a really good job with the whole system (at this point I've read a good amount of the source).

For the OpenAPI document I've been working with ([downloadable here](https://cognitohq.com/docs/reference) if you'd like although I provide a more targeted example below), we model nullability using the recommendation from [this GitHub comment on the OpenAPI spec](https://github.com/OAI/OpenAPI-Specification/issues/1368#issuecomment-580103688).

Essentially:

```yaml
# Definition
"Null":
  not:
    anyOf:
    - type: string
    - type: number
    - type: boolean
    - type: object
    - type: array

# Usage
Foobar:
  oneOf:
    - "$ref": "#/components/schemas/Description"
    - "$ref": "#/components/schemas/Null"
```

This library basically rejects `Null` as defined above as an invalid type, I assume because it (intentionally) narrows the permitted set of types down to the empty set.

## Reproduction

For ease of reproduction, I created a simplified OpenAPI document below along with a script you can run: [gist](https://gist.github.com/backus/75252df00a4f5574f19e72bebbf0bb71). You can clone and run if you want to verify, or you can look at the output I included (copied below):

```
$ ruby bug.rb

Parsing the YAML works fine:
  OpenAPI document parsed successfully

I can access each component directly and everything is fine:
  Null => Openapi3Parser::Node::Schema(#/components/schemas/Null)
  Description => Openapi3Parser::Node::Schema(#/components/schemas/Description)
  BlogPost => Openapi3Parser::Node::Schema(#/components/schemas/BlogPost)

If I access a component that uses components/schemas/Null though via a $ref, I get an error:

/Users/developer/.rbenv/versions/2.6.9/lib/ruby/gems/2.6.0/gems/openapi3_parser-0.9.2/lib/openapi3_parser/node_factory/field.rb:110:in `validate': Invalid data for #/paths/%2Fblog%2Fpost/post/responses/201/content/application%2Fjson/schema/%24ref: #/components/schemas/BlogPost does not resolve to a valid object (Openapi3Parser::Error::InvalidData)
	from /Users/developer/.rbenv/versions/2.6.9/lib/ruby/gems/2.6.0/gems/openapi3_parser-0.9.2/lib/openapi3_parser/node_factory/field.rb:86:in `data'
	from /Users/developer/.rbenv/versions/2.6.9/lib/ruby/gems/2.6.0/gems/openapi3_parser-0.9.2/lib/openapi3_parser/node_factory/field.rb:63:in `data'
	from /Users/developer/.rbenv/versions/2.6.9/lib/ruby/gems/2.6.0/gems/openapi3_parser-0.9.2/lib/openapi3_parser/node_factory/field.rb:43:in `node'
	from /Users/developer/.rbenv/versions/2.6.9/lib/ruby/gems/2.6.0/gems/openapi3_parser-0.9.2/lib/openapi3_parser/node_factory/reference.rb:48:in `build_node'
	from /Users/developer/.rbenv/versions/2.6.9/lib/ruby/gems/2.6.0/gems/openapi3_parser-0.9.2/lib/openapi3_parser/node_factory/object.rb:51:in `node'
	from /Users/developer/.rbenv/versions/2.6.9/lib/ruby/gems/2.6.0/gems/openapi3_parser-0.9.2/lib/openapi3_parser/node/placeholder.rb:49:in `node'
	from /Users/developer/.rbenv/versions/2.6.9/lib/ruby/gems/2.6.0/gems/openapi3_parser-0.9.2/lib/openapi3_parser/node/placeholder.rb:12:in `resolve'
	from /Users/developer/.rbenv/versions/2.6.9/lib/ruby/gems/2.6.0/gems/openapi3_parser-0.9.2/lib/openapi3_parser/node/object.rb:35:in `[]'
	from /Users/developer/.rbenv/versions/2.6.9/lib/ruby/gems/2.6.0/gems/openapi3_parser-0.9.2/lib/openapi3_parser/node/media_type.rb:11:in `schema'
	from bug.rb:29:in `<main>'
```

## Desired outcome

I'm opening this issue partially because I want your take here on this. Given that the recommendation I linked was from @tedepstein, I believe this is in fact a bug and not a feature. I also do realize that upgrading to v3.1 would be one way to address this, but internally we are dealing with around ~30k lines of OpenAPI YAML so upgrading is not a short term solution.

If it is a bug, I'd love to help get it patched. I could try my hand at a PR at some point assuming my hunch is right that it might be a somewhat straightforward fix.

Thanks again for writing this fantastic gem!

**Comment by kevindew** [comment]
Hey there, thanks for your kind words about this gem and for producing the steps to reproduce your problem - really helpful.

So I've found the point that causes the problem here. It is the definition for `type: array`. I found out this out by validating the document and checking the errors:

```
(byebug) doc.valid?
false
(byebug) doc.errors
Openapi3Parser::Validation::ErrorCollection(errors: {"#/paths/%2Fblog%2Fpost/post/responses/201/content/application%2Fjson/schema/%24ref"=>["#/components/schemas/BlogPost does not resolve to a valid object"], "#/components/schemas/Null/not/anyOf/4"=>["items must be defined for a type of array"], "#/components/schemas/BlogPost/properties/description/oneOf/1/%24ref"=>["#/components/schemas/Null does not resolve to a valid object"]})
```

According to the [3.0.3 specification](https://github.com/OAI/OpenAPI-Specification/blob/main/versions/3.0.3.md#schema-object):

> items - Value MUST be an object and not an array. Inline or referenced schema MUST be of a [Schema Object](https://github.com/OAI/OpenAPI-Specification/blob/main/versions/3.0.3.md#schemaObject) and not a standard JSON Schema. items MUST be present if the type is array.

At the level of this parser you can get around this with specifying any valid schema for the items attribute, it seems an empty object will suffice

```
components:
  schemas:
    "Null":
      not:
        anyOf:
          - type: string
          - type: number
          - type: boolean
          - type: object
          - type: array
            items: {}
      description: |-
        The literal value `null`.

        NOTE: This is a workaround for OpenAPI 3.0's lack of support for nullable ref types. See: https://github.com/OAI/OpenAPI-Specification/issues/1368#issuecomment-580103688
      title: "Null"
```

Hope this helps to get you moving.

---

Re: 3.1, yup the jump to that is pretty big 😬. I've still got quite a long todo list to get this gem working with 3.1

**Comment by backus** [comment]
Excellent! I think that is a much easier solution for everyone. I'll give that a try and reopen in the off chance something doesn't work

**Comment by backus** [comment]
Just confirming that solved our problem! So simple haha, thanks for helping me get to the bottom of that!
