### ISSUE TITLE
CommonMarker sec issue

### ISSUE THREAD

**Issue by waghanza** [kevindew/openapi3_parser#25]
Hi @kevindew ,

First, I want to take you for your awesome work on this library.

Might be useful to update this line https://github.com/kevindew/openapi3_parser/blob/d2d4aff7cea9827bce9b595e7b8dca9e310bb2ca/openapi3_parser.gemspec#L30.

A CVE is discovered on this dependency
https://github.com/gjtorikian/commonmarker/security/advisories/GHSA-4qw4-jpp4-8gvp

Regards,

**Comment by kevindew** [comment]
Thank you @waghanza, I've updated the dependency in d279598

As the released version is an approximate version constraint and doesn't prevent the installation of a safe version (0.23.6) I'm not going to release this change instantly and instead ship it next time a release is needed.

Thanks for your kind words on this project 🖖
