### ISSUE TITLE
Wrong parsing false defaults 

### ISSUE THREAD

**Issue by seorgiy** [kevindew/openapi3_parser#28]
Hey!

```
  document = Openapi3Parser.load_url("https://ark0f.github.io/tg-bot-api/openapi.json") 
  p document.node_at("#/components/schemas/Error/properties/ok/type") 
```
Expected behavior: false
In fact: nil

**Comment by kevindew** [comment]
Hey, sorry for taking ages to get back to you.

I've just tried this myself and was able to replicate your issue (albeit with the pointer as "#/components/schemas/Error/properties/ok/default").

I've just pushed up https://github.com/kevindew/openapi3_parser/commit/975ade0c609c5196ad540bb75952fa9afa55960e to fix it and will push it out on the next release.

Thanks for taking the time to report the issue.
