### ISSUE TITLE
lots of Warnings 

### ISSUE THREAD

**Issue by Electron-libre** [kevindew/openapi3_parser#6]
Ruby warns about unitialized variables
Even if  code is works fine, these warnings are enoying

```
openapi3_parser-0.5.1/lib/openapi3_parser/node_factory/object_factory/dsl.rb:36: warning: instance variable @mutually_exclusive not initialized
````

**Comment by Electron-libre** [comment]
I've spotted most of them.
I still having some warning around cicular dependencies in require
but i'll submit a PR when it's done.

**Comment by kevindew** [comment]
Thanks! I had a go last night too and might have caught them all: https://github.com/kevindew/openapi3_parser/tree/fix-warnings

I changed the require approach to remove the cyclic dependencies.

Annoyingly I can't seem to get the warnings to alert with rspec 😕 which would make more confident I don't introduce new ones.

**Comment by Electron-libre** [comment]
You just have to check your spec helper and change the warning boolean 

https://github.com/kevindew/openapi3_parser/blob/master/spec/spec_helper.rb#L9

**Comment by kevindew** [comment]
Oh dang! that explains why all my attempts to add warnings in failed. Thanks I'll get that removed.
